#!/bin/bash
set -euo pipefail

# retrieve current branch name
git rev-parse --abbrev-ref HEAD > public/branch_name.dev.txt

# retrieve current commit short hash
git rev-parse --short HEAD > public/version.dev.txt
# and append pretty colored stats
git diff --shortstat --format='' HEAD \
  | awk '{
          ins=0; del=0;
          for (i=1; i<=NF; i++) {
            if ($(i+1) ~ /^insertion/) ins=$i;
            if ($(i+1) ~ /^deletion/)  del=$i;
          }
          printf("<span class=\"ins\">+%d</span>/<span class=\"del\">-%d</span>", ins, del);
        }' \
  >> public/version.dev.txt